using UnityEngine;

public class VRButtonInteraction : MonoBehaviour
{
    private Renderer buttonRenderer; // 按o的RendererM件
    public Color highlightedColor = Color.red; // 按o被x中r的色
    private Color originalColor; // 按o的原始色

    void Start()
    {
        buttonRenderer = GetComponent<Renderer>();
        if (buttonRenderer != null)
        {
            originalColor = buttonRenderer.material.color; // 保存原始色
        }
    }

    void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("VRController"))
        {
            // VR手柄接近按o，改色
            buttonRenderer.material.color = highlightedColor;
        }
    }

    void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("VRController"))
        {
            // VR手柄hx按o，恢驮始色
            buttonRenderer.material.color = originalColor;
        }
    }
}